# Generated by Django 5.1.4 on 2025-02-20 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='sent_at',
            new_name='created_at',
        ),
    ]
